version: "3"

services:
  client:
    build:
      context: .
    image: file-manager-client-app
    container_name: file-manager-client-container
    restart: always
    volumes:
      - ./certbot/www:/var/www/certbot:ro
      - ./certbot/conf:/etc/letsencrypt:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
      - "443:443"
    networks:
      - file-manager-network

  certbot:
    image: certbot/certbot
    container_name: certbot-container
    restart: always
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot-entrypoint.sh:/certbot-entrypoint.sh:ro
    entrypoint: sh /certbot-entrypoint.sh
    environment:
      - DOMAIN=filemanager.valentinpopescu.com
      - EMAIL=contact@valentinpopescu.com
      - CHECK_INTERVAL=86400
    networks:
      - file-manager-network
    depends_on:
      - client

networks:
  file-manager-network:
    external: true
